name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "0.34.1"
          rebar3-version: "3"
      - run: bun i --frozen-lockfile
      - run: gleam deps download
      - run: bun run build
      - uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: dist/
